# Runner
FROM nginx:1.23-alpine AS runner
COPY ./css /usr/share/nginx/html/css
COPY ./js /usr/share/nginx/html/js
COPY ./img /usr/share/nginx/html/img
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./k8s/nginx.conf /etc/nginx/conf.d/default.conf

RUN apk update
RUN apk upgrade

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
